users:
  hosts:
    user:
      ansible_host: 172.16.99.99
      ingress_ip: 10.0.0.222/24
      keepalive_ip: false

loadbalancers:
  hosts:
    lb1:
      ansible_host: 172.16.99.2
      ingress_ip: 10.0.0.2/24
      keepalive_ip: 10.1.0.2/24
      vrrp_initial_state: MASTER
    lb2:
      ansible_host: 172.16.99.3
      ingress_ip: 10.0.0.3/24
      keepalive_ip: 10.1.0.3/24
      vrrp_initial_state: BACKUP

webservers:
  hosts:
    web1:
      ansible_host: 172.16.99.101
      ingress_ip: 10.0.0.101/24
      keepalive_ip: 10.1.0.101/24
    web2:
      ansible_host: 172.16.99.102
      ingress_ip: 10.0.0.102/24
      keepalive_ip: 10.1.0.102/24
    web3:
      ansible_host: 172.16.99.103
      ingress_ip: 10.0.0.103/24
      keepalive_ip: 10.1.0.103/24

all:
  vars:
    ansible_user: testbed
    ansible_password: 1
    ingress_if: eth1
    keepalive_if: eth2
    virtual_service_ip: 10.0.0.200/24
